#!/usr/bin/env bash

## Load the current Tiel Standard configuration.
readonly MAIN_CONF="$HOME/.config/tiel-standard/main.conf"
source $MAIN_CONF

## If we are not supposed to cycle wallpapers, load the default one.
if [ "$RANDOMIZE_DESKTOP" = false ]; then
  nitrogen --restore &
  betterlockscreen -w &

## Update the desktop background and select a new lock image.
else
  betterlockscreen -u ~/Pictures/Wallpapers/ & betterlockscreen -w &
fi

## xfce4-settings daemon
xfsettingsd &

## TODO: genericize to 2+ monitors.
## Automatically setup dual monitors if they exist.
SCREEN_COUNT=$(xrandr --listmonitors | sed -n "1"p | awk '{print $NF}')
if [ "$SCREEN_COUNT" -gt 1 ]; then
  SCREEN_ONE=$(xrandr --listmonitors | sed -n "2"p | awk '{print $NF}')
  SCREEN_TWO=$(xrandr --listmonitors | sed -n "3"p | awk '{print $NF}')
  xrandr --output $SCREEN_TWO --auto --output $SCREEN_ONE --auto --right-of $SCREEN_TWO
fi

## Start Compositing Manager
exec compton -b &

## Launch Polybar
sh ~/.config/polybar/launch.sh

## Start Music Player Daemon
exec mpd &

## Notification Daemon
exec dunst &

## Thunar Daemon
exec thunar --daemon &

## Start Autoplank.
/usr/local/bin/autoplank &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

## Enable power management
xfce4-power-manager &

## Synchronize with Unison.
sync-unison.sh &
