#!/usr/bin/env bash

## Load the current Tiel Standard configuration.
readonly MAIN_CONF="$HOME/.config/tiel-standard/main.conf"
source $MAIN_CONF

## If we are not supposed to cycle wallpapers, load the default one.
if [ "$RANDOMIZE_DESKTOP" = false ]; then
  nitrogen --restore &
  betterlockscreen -w &

## Update the desktop background and select a new lock image.
else
  betterlockscreen -u ~/Pictures/Wallpapers/ & betterlockscreen -w &
fi

## xfce4-settings daemon
xfsettingsd &

## Start Compositing Manager
exec compton -b &

## Launch Polybar
sh ~/.config/polybar/launch.sh

## Launch Plank
exec autoplank.sh &

## Start Music Player Daemon
exec mpd &

## Notification Daemon
exec dunst &

## Thunar Daemon
exec thunar --daemon &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

## Enable power management
xfce4-power-manager &
